### ISSUE TITLE
adding a plugin by default prettier-plugin-tailwindcss (cra, nextjs, vite)

### ISSUE THREAD

**Issue by SergeITinc** [tzsk/twify#40]
https://github.com/tailwindlabs/prettier-plugin-tailwindcss

Please add this default plugin to as a dev-dependency. (cra, nextjs, vite)

Or as a suggestion - to add such an option. 
How have you done to preserve CSS.   option('-p, --preserve', 'Preserve existing CSS') or whatever :)

Because a lot of people have to do it every time anyway.

Thanks.

**Comment by tzsk** [comment]
@SergeITinc Released `v.0.3.1`

**Comment by SergeITinc** [comment]
@tzsk  Thank you so much!
